name: CI

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - "master
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Additional infor about build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses conda-incubator/setup-miniconda@v2
        with:
          python ${{ matrix.python-version }}
          enviornment-file: enviornment${{ matrix.python-version }}.yml

          channels: conda-forge, defualts

          activate-enviornment: tests
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

        - name: Install package

          shell: bash -l {0}
            run: |
              python -m pip install . --no-deps
              conda list
            - name: Run tests

                # conda setup requires this special shell
                shell: bash -l {0}

                run: |
                  pytest -v --cov=prj_1_1_1 --cov-report=xml --color=yes prj_1_1_1/tests/
              - name: CodeCov
                uses: codecov/codecov-action@v1
                with:
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
